config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users
  resources :customers

  root                    'sessions#new'
  get    'add_account' => 'accounts#new'
  get    'signup'      => 'users#new'
  get    'login'       => 'sessions#new'
  post   'login'       => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'
  get    'dashboard'   => 'static_pages#dashboard'
  get    'list_accounts' => 'customers#list_accounts'
  # Will do this correctly (add logic to main dash) later
  #TODO Fix format -> id in route
  get    'customer_dashboard'   => 'customers#dashboard'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :accounts, dependent: :destroy
  has_many :contacts

  validates :name, presence: true

  def list_account_names()
    self.accounts.map {|account| account.name}
    #Account.where(:customer_id => self.id).map {|account| account.name}
  end

  def list_account_numbers()
    self.accounts.map {|account| account.account_number}
    #Account.where(:customer_id => self.id).map {|account| account.account_number}
  end

  # def list_customer_accounts()
  #   Account.where(:customer_id => self.id)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
    @accounts = Account.all
    @current_account = Account.find_by(params[:id])
  end

  def edit
  end

  def show
    @customer_names = @customer.list_account_names
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to dashboard_path}
        flash[:success] = 'Customer was successfully added.'
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer }
        flash[:success] = 'Customer was successfully updated.'
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path}
      flash[:success] = 'Customer was successfully deleted.'
    end
  end

  def dashboard
    @customer = Customer.find(params[:format])
  end

  def list_accounts
    @customer = Customer.find(params[:format])
    @customer_accounts = @customer.accounts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/dashboard.html.erb
<% provide(:title, "Customer Dasboard") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | WatchTower Dashboard</title>
  </head>
    <body>
      <%= render 'layouts/sidebar', :customers => Customer.all %>

       <h1 class="sub-header">Triggered Alerts for <%= @customer.name %></h1>
       <div class="table-responsive">
         <table class="table table-striped">
           <thead>
             <tr>
               <th>Alert Name</th>
               <th>Details</th>
               <th>Customer/Account</th>
               <th>Audit Entries</th>
               <th>Launch in CM</th>
             </tr>
           </thead>
           <tbody>
             <tr>
               <td>1,001</td>
               <td>Lorem</td>
               <td>ipsum</td>
               <td>dolor</td>
               <td>sit</td>
             </tr>
             <tr>
               <td>1,002</td>
               <td>amet</td>
               <td>consectetur</td>
               <td>adipiscing</td>
               <td>elit</td>
             </tr>
             <tr>
               <td>1,003</td>
               <td>Integer</td>
               <td>nec</td>
               <td>odio</td>
               <td>Praesent</td>
             </tr>
             <tr>
               <td>1,003</td>
               <td>libero</td>
               <td>Sed</td>
               <td>cursus</td>
               <td>ante</td>
             </tr>
             <tr>
               <td>1,004</td>
               <td>dapibus</td>
               <td>diam</td>
               <td>Sed</td>
               <td>nisi</td>
             </tr>
             <tr>
               <td>1,005</td>
               <td>Nulla</td>
               <td>quis</td>
               <td>sem</td>
               <td>at</td>
             </tr>
             <tr>
               <td>1,006</td>
               <td>nibh</td>
               <td>elementum</td>
               <td>imperdiet</td>
               <td>Duis</td>
             </tr>
             <tr>
               <td>1,007</td>
               <td>sagittis</td>
               <td>ipsum</td>
               <td>Praesent</td>
               <td>mauris</td>
             </tr>
           </table>


             <h1 class="sub-header">All Alerts for <%= @customer.name %></h1>
             <div class="table-responsive">
               <table class="table table-striped">
                 <thead>
                   <tr>
                     <th>Alert Name</th>
                     <th>Details</th>
                     <th>Customer/Account</th>
                     <th>Audit Entries</th>
                     <th>Launch in CM</th>
                   </tr>
                 </thead>
                 <tbody>
                   <tr>
                     <td>1,001</td>
                     <td>Lorem</td>
                     <td>ipsum</td>
                     <td>dolor</td>
                     <td>sit</td>
                   </tr>
                   <tr>
                     <td>1,002</td>
                     <td>amet</td>
                     <td>consectetur</td>
                     <td>adipiscing</td>
                     <td>elit</td>
                   </tr>
                   <tr>
                     <td>1,003</td>
                     <td>Integer</td>
                     <td>nec</td>
                     <td>odio</td>
                     <td>Praesent</td>
                   </tr>

           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>

       <!-- Bootstrap core JavaScript
       ================================================== -->
       <!-- Placed at the end of the document so the pages load faster -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
       <script src="../../dist/js/bootstrap.min.js"></script>
       <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
       <script src="../../assets/js/vendor/holder.js"></script>
       <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
       <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
     </body>
   </html>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table class="table table-striped">
  <tr>
    <th>Customer Name</th>
    <th>Account Name</th>
    <th>Account Number</th>
    <th>Actions</th>
  </tr>

<!-- Show each customer in the table with Edit and Delete options -->

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= customer.list_account_names.join(',')%>
        <td><%= customer.list_account_numbers.join(',')%>
      <td><%= link_to 'Add Account', new_account_path(@current_account) %> |
          <%= link_to 'Edit', edit_customer_path(customer.id) %> |
          <%= link_to 'Delete', customer_path(customer), method: :delete,
           data: {confirm: 'Are you sure?'} %>
          <%#= link_to 'Add/Update Account', edit_account_path(@current_account) %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/list_accounts.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts for <%= @customer.name %></h1>


<table class="table table-striped">
  <tr>
    <th>Account Name</th>
    <th>Account Number</th>
    <th>Actions</th>
  </tr>

<!-- Show each account in the table with Edit and Delete options -->

  <% @customer_accounts.each do |account| %>
    <tr>
      <td><%= account.name %></td>
      <td><%= account.account_number %></td>
      <td><%= link_to 'Edit', edit_account_path(account.id) %> |
          <%= link_to 'Delete', account_path(account), method: :delete,
          data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Add Account', new_account_path(:customer_id => @customer.id) %>

app/views/customers/new.html.erb
<% provide(:title, 'Add Customer') %>

<h1>Add Customer</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@customer) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/customers/show.html.erb
<p>
  <strong>Customer Account:</strong>
  <%= @customer.name %>
</p>

<% provide(:title, "Customer Account: #{@customer.name}") %>
<%= link_to "Add Account", new_account_path %>
<%= link_to "Add Account Test", new_account_path(:customer_id => @customer.id) %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | WatchTower Dashboard</title>
  </head>
    <body>
      <%= render 'layouts/sidebar' %>

       <h1 class="sub-header">Triggered Alerts</h1>
       <div class="table-responsive">
         <table class="table table-striped">
           <thead>
             <tr>
               <th>Alert Name</th>
               <th>Details</th>
               <th>Customer/Account</th>
               <th>Audit Entries</th>
               <th>Launch in CM</th>
             </tr>
           </thead>
           <tbody>
             <tr>
               <td>1,001</td>
               <td>Lorem</td>
               <td>ipsum</td>
               <td>dolor</td>
               <td>sit</td>
             </tr>
             <tr>
               <td>1,002</td>
               <td>amet</td>
               <td>consectetur</td>
               <td>adipiscing</td>
               <td>elit</td>
             </tr>
             <tr>
               <td>1,003</td>
               <td>Integer</td>
               <td>nec</td>
               <td>odio</td>
               <td>Praesent</td>
             </tr>
             <tr>
               <td>1,003</td>
               <td>libero</td>
               <td>Sed</td>
               <td>cursus</td>
               <td>ante</td>
             </tr>
             <tr>
               <td>1,004</td>
               <td>dapibus</td>
               <td>diam</td>
               <td>Sed</td>
               <td>nisi</td>
             </tr>
             <tr>
               <td>1,005</td>
               <td>Nulla</td>
               <td>quis</td>
               <td>sem</td>
               <td>at</td>
             </tr>
             <tr>
               <td>1,006</td>
               <td>nibh</td>
               <td>elementum</td>
               <td>imperdiet</td>
               <td>Duis</td>
             </tr>
             <tr>
               <td>1,007</td>
               <td>sagittis</td>
               <td>ipsum</td>
               <td>Praesent</td>
               <td>mauris</td>
             </tr>
           </table>


             <h1 class="sub-header">All Alerts</h1>
             <div class="table-responsive">
               <table class="table table-striped">
                 <thead>
                   <tr>
                     <th>Alert Name</th>
                     <th>Details</th>
                     <th>Customer/Account</th>
                     <th>Audit Entries</th>
                     <th>Launch in CM</th>
                   </tr>
                 </thead>
                 <tbody>
                   <tr>
                     <td>1,001</td>
                     <td>Lorem</td>
                     <td>ipsum</td>
                     <td>dolor</td>
                     <td>sit</td>
                   </tr>
                   <tr>
                     <td>1,002</td>
                     <td>amet</td>
                     <td>consectetur</td>
                     <td>adipiscing</td>
                     <td>elit</td>
                   </tr>
                   <tr>
                     <td>1,003</td>
                     <td>Integer</td>
                     <td>nec</td>
                     <td>odio</td>
                     <td>Praesent</td>
                   </tr>

           </tbody>
         </table>
       </div>
     </div>
   </div>
 </div>

       <!-- Bootstrap core JavaScript
       ================================================== -->
       <!-- Placed at the end of the document so the pages load faster -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
       <script src="../../dist/js/bootstrap.min.js"></script>
       <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
       <script src="../../assets/js/vendor/holder.js"></script>
       <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
       <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
     </body>
   </html>