config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users
  resources :customers

  root                    'sessions#new'
  get    'add_account' => 'accounts#new'
  get    'signup'      => 'users#new'
  get    'login'       => 'sessions#new'
  post   'login'       => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'
  get    'dashboard'   => 'static_pages#dashboard'
  get    'list_accounts' => 'customers#list_accounts'
  # Will do this correctly (add logic to main dash) later
  #TODO Fix format -> id in route
  get    'customer_dashboard'   => 'customers#dashboard'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   WatchTower is pretty sweet.
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <div class="container">
  <%= link_to "WatchTower", dashboard_path, id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "#{current_user.name.upcase}", '#' %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
    </ul>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
</div>

</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li class="active"><a href="#"> <span class="sr-only">(current)</span></a></li>
        <li><a href="customers/new"><strong>Add A Customer</strong></a></li>
        <% customers.each do |customer| %>
        <div class="btn-group">
            <a href="customer_dashboard.<%=customer.id%>" class="btn btn-default custom" role="button"><%= customer.name %></a>
          <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
            <span class="caret"></span>
            <span class="sr-only">Toggle Dropdown</span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><a href="list_accounts.<%=customer.id%>">Manage Accounts</a></li>
            <li><a href="customer_dashboard.<%=customer.id%>">Manage Alerts</a></li>
            <li><%= link_to 'Delete Customer', customer_path(customer), method: :delete,
             data: {confirm: 'Are you sure?'} %></li>
          </ul>
        </div>
        <% end %>
      </ul>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%#= debug(params) if Rails.env.development? %>
  </div>
    <%#= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>