config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :users
  resources :customers

  root                    'sessions#new'
  get    'add_account' => 'accounts#new'
  get    'signup'      => 'users#new'
  get    'login'       => 'sessions#new'
  post   'login'       => 'sessions#create'
  delete 'logout'      => 'sessions#destroy'
  get    'dashboard'   => 'static_pages#dashboard'
  get    'list_accounts' => 'customers#list_accounts'
  # Will do this correctly (add logic to main dash) later
  #TODO Fix format -> id in route
  get    'customer_dashboard'   => 'customers#dashboard'
end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :customer

  validates :account_number, presence: true, length: { is: 5 }
  validates :name, presence: true
  validates :customer_id, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = Account.all
    @customers = Customer.all
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
    @customers = Customer.all
  end

  def edit
  end

  def create
    @account = Account.new(account_params)
    @customers = Customer.all

    respond_to do |format|
      if @account.save
        format.html { redirect_to dashboard_path }
        flash[:success] = 'Account was successfully created.'
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account }
        flash[:success] = 'Customer was successfully updated.'
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url }
      flash[:success] = 'Customer was successfully deleted.'
      #format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    def account_params
      params.require(:account).permit(:name, :account_number, :customer_id)
    end
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account_number %><br>
    <%= f.number_field :account_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>


<table class="table table-striped">
  <tr>
    <th>Customer Name</th>
    <th>Customer ID</th>
    <th>Account Name</th>
    <th>Account Number</th>
    <th>Actions</th>
  </tr>

<!-- Show each account in the table with Edit and Delete options -->

  <% @accounts.each do |account| %>
    <tr>
      <td><%= account.customer.name %></td>
      <td><%= account.customer.id %></td>
      <td><%= account.name %></td>
      <td><%= account.account_number %></td>
      <td><%= link_to 'Edit', edit_account_path(account.id) %> |
          <%= link_to 'Delete', account_path(account), method: :delete,
          data: {confirm: 'Are you sure?'} %>
      </td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'Add Account', new_account_path %>

app/views/accounts/new.html.erb
<% provide(:title, 'Add Account') %>
<h1>Add Account</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@account) do |f| %>
    <%= render 'shared/error_messages' %>

      <div class="form-group">

      <%= f.label :account_name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :account_number %>
      <%= f.text_field :account_number, class: 'form-control' %>


      <%= f.hidden_field :customer_id, class: 'form-control', value: params[:customer_id] %>

      <%= f.submit "Add Account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @account.account_number %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>